### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by HDK101** [HDK101/express-blog#1]
- [x] Develop pages which creates,updates and delete admins 
- [x] Code tests for admins
- [x] Validation for all models
- [x] Refactor code
